[phases.setup]
nixPkgs = ['nodejs-18.x', 'npm']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'node server.js'

[build.environment]
NODE_ENV = "production"

[build.args]
RAILWAY_ENVIRONMENT = "production"
